import type { NextApiRequest, NextApiResponse } from 'next';
import clientPromise from '../../../lib/mongodb';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '../auth/[...nextauth]';

import { withErrorHandler } from '../../../lib/withErrorHandler';

async function handler(req: NextApiRequest, res: NextApiResponse) {
  const session = await getServerSession(req, res, authOptions);
  const { secret } = req.query;
  
  // Allow if they have the secret OR if they are an authenticated admin
  if (secret !== (process.env.CRON_SECRET || 'humours-daily') && session?.user?.role !== 'admin') {
    return res.status(401).json({ message: 'Unauthorized' });
  }

  const webhookUrl = process.env.DISCORD_DIGEST_WEBHOOK_URL || process.env.DISCORD_WEBHOOK_URL;
  if (!webhookUrl) {
    return res.status(500).json({ message: 'Discord webhook not configured' });
  }

  try {
    const client = await clientPromise;
    const db = client.db();

    // Get today's start and end times
    const startOfDay = new Date();
    startOfDay.setHours(0, 0, 0, 0);
    
    const endOfDay = new Date();
    endOfDay.setHours(23, 59, 59, 999);

    const dateQuery = { createdAt: { $gte: startOfDay, $lte: endOfDay } };

    // 1. Fetch Bookings
    const bookings = await db.collection('bookings').find(dateQuery).toArray();
    const confirmed = bookings.filter(b => b.status === 'approved');
    const pending = bookings.filter(b => b.status === 'pending');
    const cancelled = bookings.filter(b => b.status === 'cancelled');

    const confirmedRevenue = confirmed.reduce((sum, b) => {
      if (b.cart && b.cart.length > 0) {
        return sum + b.cart.reduce((s: number, item: any) => s + (item.price || 0), 0);
      }
      return sum;
    }, 0);

    const conversionRate = bookings.length > 0 ? Math.round((confirmed.length / bookings.length) * 100) : 0;

    // 2. Fetch Other Stats
    const newComedians = await db.collection('comedians').find({ 
      createdAt: { $gte: startOfDay, $lte: endOfDay } 
    }).toArray();
    
    const newFeedbacks = await db.collection('feedbacks').find({ 
      createdAt: { $gte: startOfDay, $lte: endOfDay } 
    }).toArray();

    const payload = {
      embeds: [{
        title: "🌙 Daily Operations Digest",
        color: 9807270, // #95A5A6 (Gray/Silver)
        description: `Here is your end-of-day summary for ${startOfDay.toLocaleDateString()}.`,
        fields: [
          { name: '💰 Total Revenue', value: `₹${confirmedRevenue.toLocaleString()}`, inline: true },
          { name: '🎟️ Total Bookings', value: `${confirmed.length} confirmed`, inline: true },
          { name: '📈 Conversion Rate', value: `${conversionRate}%`, inline: true },
          { name: '❌ Cancelled / Drop-offs', value: `${cancelled.length + pending.length}`, inline: true },
          { name: '👥 New Applications', value: `${newComedians.length}`, inline: true },
          { name: '💬 New Feedbacks', value: `${newFeedbacks.length}`, inline: true }
        ],
        footer: { text: "⚡️ Generated by Humours Hub Auto-Cron" }
      }]
    };

    await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });

    return res.status(200).json({ success: true, message: 'Digest sent to Discord' });
  } catch (error: any) {
    console.error('Daily Digest Error:', error);
    return res.status(500).json({ message: 'Internal server error' });
  }
}

export default withErrorHandler(handler);
