import type { NextApiRequest, NextApiResponse } from 'next';
import clientPromise from '../../../lib/mongodb';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '../auth/[...nextauth]';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const session = await getServerSession(req, res, authOptions);
  const { secret } = req.query;
  
  // Allow if they have the secret OR if they are an authenticated admin
  if (secret !== (process.env.CRON_SECRET || 'humours-daily') && session?.user?.role !== 'admin') {
    return res.status(401).json({ message: 'Unauthorized' });
  }

  const webhookUrl = process.env.SLACK_DIGEST_WEBHOOK_URL || process.env.SLACK_WEBHOOK_URL;
  if (!webhookUrl) {
    return res.status(500).json({ message: 'Slack webhook not configured' });
  }

  try {
    const client = await clientPromise;
    const db = client.db();

    // Get today's start and end times
    const startOfDay = new Date();
    startOfDay.setHours(0, 0, 0, 0);
    
    const endOfDay = new Date();
    endOfDay.setHours(23, 59, 59, 999);

    const dateQuery = { createdAt: { $gte: startOfDay, $lte: endOfDay } };

    // 1. Fetch Bookings
    const bookings = await db.collection('bookings').find(dateQuery).toArray();
    const confirmed = bookings.filter(b => b.status === 'approved');
    const pending = bookings.filter(b => b.status === 'pending');
    const cancelled = bookings.filter(b => b.status === 'cancelled');

    const confirmedRevenue = confirmed.reduce((sum, b) => {
      if (b.cart && b.cart.length > 0) {
        return sum + b.cart.reduce((s: number, item: any) => s + (item.price || 0), 0);
      }
      return sum;
    }, 0);

    const conversionRate = bookings.length > 0 ? Math.round((confirmed.length / bookings.length) * 100) : 0;

    const message = {
      attachments: [
        {
          color: '#3498DB',
          blocks: [
            {
              type: 'header',
              text: {
                type: 'plain_text',
                text: '🌙 Daily Operations Digest',
                emoji: true
              }
            },
            {
              type: 'section',
              text: {
                type: 'mrkdwn',
                text: `*Here is your end-of-day summary for ${startOfDay.toLocaleDateString()}:*`
              }
            },
            {
              type: 'divider'
            },
            {
              type: 'section',
              fields: [
                { type: 'mrkdwn', text: `*💰 Total Revenue*\n₹${confirmedRevenue.toLocaleString()}` },
                { type: 'mrkdwn', text: `*📈 Conversion Rate*\n${conversionRate}%` },
                { type: 'mrkdwn', text: `*✅ Confirmed Bookings*\n${confirmed.length}` },
                { type: 'mrkdwn', text: `*🚫 Cancelled / Drop-offs*\n${cancelled.length + pending.length}` }
              ]
            },
            {
              type: 'context',
              elements: [
                {
                  type: 'mrkdwn',
                  text: '⚡️ Generated by Humours Hub Auto-Cron'
                }
              ]
            }
          ]
        }
      ]
    };

    await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(message)
    });

    return res.status(200).json({ success: true, message: 'Digest sent to Slack' });
  } catch (error: any) {
    console.error('Daily Digest Error:', error);
    return res.status(500).json({ message: 'Internal server error' });
  }
}
